### ISSUE TITLE
Insertion of tactics

### ISSUE THREAD

**Issue by m-fleury** [m-fleury/isabelle-release#19]
In dc00d20, you @gh-salt  have added support to add try0/by simp/by auto/by blast.

I am curious if you really use them. Personally, I am rarely sure enough about auto/simp/blast to directly insert a `by auto`.  I have, however, thought about writing a function that replaces `apply XXX` by `by XXX`.

I am just curious about the use case. (You probably should answer only in one week after really trying them out ;-))

**Comment by gh-salt** [comment]
Exactly. Since I use try0 a lot and like to add any of the various options it gives, I want to test if it is more convenient to use such shortcuts than type them after a try0 call. I will try like this and in a few days (or more likely in a week or two) I will see if it is worth generalizing this to all tactics tested by try0...

...At least that was the plan before you opened #18 which I seems also very promising.

Maybe having both would still make sense, e.g. I sometimes write a detailed proof and see if all goals can be solved by the same tactic to find out which additional lemmas are needed before shortening the proof to a "using ... by ...". In that particular case, you may not want to always select the tactic suggested by try0 so my approach could make sense.
