### ISSUE TITLE
"local" bug

### ISSUE THREAD

**Issue by gh-salt** [m-fleury/isabelle-release#28]
More of a memo than a bug report.

This is an old one from before github.
Although we thought this bug was fixed, it still has various effects:
* number of proof goals to verifiy that is indicated doubles
* when using `Alt-/` the evaluation of the file by lsp restarts from the top of the file.

Issue: This is all due to the fact that on my system `/home` is an alias for `/local/home` and emacs somehow sees two files instead of one.

**Comment by m-fleury** [comment]
It is Isabelle that sees two files, because the path normalization is done differently in emacs and Isabelle (and most probably inconsistently in the latter).

**Comment by m-fleury** [comment]
The LSP server uses `JFile.absolute_path` while the rest of Isabelle uses `JFile.canonical_path`. Given the [documentation](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#getCanonicalPath()), the difference seems to (potentially, maybe) be in the normalization of soft links.

Could you try
```
sed -i "s/absolute_path/canonical_path/g" isabelle-release/src/Tools/VSCode/src/protocol.scala
```
and see if it still happens?

**Comment by gh-salt** [comment]
Tested.
Both behaviours still happen.

**Comment by m-fleury** [comment]
Turns out I can actually reproduce it :partying_face: 

If I want to do it on the emacs side, I need to replace some `(buffer-file-name)` by `(file-truename (buffer-file-name))`. This will get kind of ugly though, because I have to touch some internal emacs-lsp functions.

Anyhow, things become a lot easier to fix now!

**Comment by m-fleury** [comment]
The problems is more complicated than that: normalizing the path while sending messages is not sufficient because emacs-lsp considers `/path0/to/file` and `/link/to/path0/to/file` to be different projects and hence start another isabelle instance. I have either to open an issue on the LSP project or find another way to do it.

**Comment by m-fleury** [comment]
As a temporary workaround (better than creating new files and so on):

``
;; This function does not properly normalize names and Isabelle is not
;; compatible with it.
(defun lsp-isar-expand-file-name (old-fun &rest file)
  (file-truename (apply old-fun file)))

(advice-add 'expand-file-name :around #'lsp-isar-expand-file-name)
``

The obvious drawback is that this changes the behaviour of every occurrence of `expand-file-name`, but that should not be an issue.
