### ISSUE TITLE
lsp-isar-state sometimes empty

### ISSUE THREAD

**Issue by gh-salt** [m-fleury/isabelle-release#29]
Since I pulled the last changes this morning, (commit 28f32fde81) for some commands, the current state is not printed. lsp-isar-state is simply blank (it could also be that it takes extremely long to get the value)

I am observing this in a proof with a sequence of "apply". For some of them the state is printed, for some it isn't.

**Comment by m-fleury** [comment]
I believe that this is linked to the asynchronous goal printing (#8), but I have never managed to reproduce those bugs… Usually going up and down fixes the issue…

Long answer: we use emacs-async (because I never found another library that does what I want), but it is way too asynchronous for my taste. It launches a new emacs instances, gets the result back, and stops the emacs instance. In particular, I believe that (at least some) error messages get lost…

If you can reproduce it:
  - I would like to know the value of the variables `content` and `result` in `lsp-isar-output--update-state-and-output-buffer-async` (e.g., by adding a `(message "content = %s" content)` and re-evaluating the function)
